import { cn } from "@/lib/utils/cn";

/**
 * Inlines a drawing from src/lib/art.ts. The wrapper is `display: contents`
 * (the `.sx` class), so the <svg> lays out as if it were the container's own
 * child — the cover, tile and avatar rules in globals.css target it that way.
 *
 * The markup is generated by our own pure functions from fixed shapes; the
 * only outside text in it (an expert's initials) is escaped there.
 */
export function Svg({ markup, className }: { markup: string; className?: string }) {
  return <span aria-hidden className={cn("sx", className)} dangerouslySetInnerHTML={{ __html: markup }} />;
}
